compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

httpTimeout: 600000

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm
    - arm64
    - ia32
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.9.2.cjs
